.PHONY: help tooling-install frontend-install frontend-ci-install frontend-check frontend-build frontend-dev backend-sync backend-ci-sync backend-lock backend-db-upgrade backend-db-revision backend-lint backend-test backend-api-dev backend-worker-run ci dev-services-up dev-services-down dev-services-reset dev-services-logs

help:
	@printf "%s\n" \
	"Optimark workspace commands" \
	"" \
	"  make dev-services-up   Start Postgres, Redis, and SeaweedFS for local development" \
	"  make dev-services-down Stop the local development services" \
	"  make dev-services-reset Stop and remove local development service volumes" \
	"  make dev-services-logs Tail logs for the local development services" \
	"  make tooling-install   Install repo-level tooling such as Husky and commitlint" \
	"  make frontend-install  Install repo tooling and Bun dependencies for the frontend workspace" \
	"  make frontend-ci-install Install frontend dependencies with a frozen lockfile" \
	"  make frontend-check    Typecheck the frontend workspace" \
	"  make frontend-build    Build the frontend workspace" \
	"  make frontend-dev      Run the frontend workspace dev script" \
	"  make backend-sync      Sync the uv backend workspace" \
	"  make backend-ci-sync   Sync the uv backend workspace with the frozen lockfile" \
	"  make backend-lock      Refresh the backend uv lockfile" \
	"  make backend-db-upgrade Apply Alembic migrations to the configured backend database" \
	"  make backend-db-revision message='...' Create a new autogenerated Alembic revision" \
	"  make backend-lint      Lint the backend workspace with Ruff" \
	"  make backend-test      Run backend pytest tests" \
	"  make backend-api-dev   Run the FastAPI backend app with reload" \
	"  make backend-worker-run Run the worker bootstrap command" \
	"  make ci                Run the baseline local CI quality gates"

dev-services-up:
	docker compose up -d

dev-services-down:
	docker compose down

dev-services-reset:
	docker compose down --volumes --remove-orphans

dev-services-logs:
	docker compose logs -f

tooling-install:
	bun install

frontend-install: tooling-install
	cd frontend && bun install

frontend-ci-install:
	cd frontend && bun install --frozen-lockfile

frontend-check:
	cd frontend && bun run check

frontend-build:
	cd frontend && bun run build

frontend-dev:
	cd frontend && bun run dev

backend-sync:
	cd backend && uv sync --all-packages

backend-ci-sync:
	cd backend && uv sync --all-packages --frozen

backend-lock:
	cd backend && uv lock

backend-db-upgrade:
	cd backend && uv run --frozen alembic upgrade head

backend-db-revision:
	@test -n "$(message)" || (echo 'usage: make backend-db-revision message="describe change"' && exit 1)
	cd backend && uv run --frozen alembic revision --autogenerate -m "$(message)"

backend-lint:
	cd backend && uv run --frozen ruff check .

backend-test:
	cd backend && uv run --frozen pytest

backend-api-dev:
	cd backend && uv run --package athena uvicorn optimark_athena.app:app --reload

backend-worker-run:
	cd backend && uv run --package hermes hermes-worker

ci:
	$(MAKE) frontend-ci-install
	$(MAKE) frontend-check
	$(MAKE) frontend-build
	$(MAKE) backend-ci-sync
	$(MAKE) backend-lint
	$(MAKE) backend-test
