// Generated by `bun run generate:api`.
// Do not edit this file manually.

import { requestJson, requestVoid } from "./client";
export type AssignmentDetail = {
  id: string;
  course_id: string;
  title: string;
  assignment_type: AssignmentType;
  publish_state: AssignmentPublishState;
  description: string;
  created_at: string;
  updated_at: string;
};

export type AssignmentPublishState = "draft" | "published" | "archived";

export type AssignmentSummary = {
  id: string;
  course_id: string;
  title: string;
  assignment_type: AssignmentType;
  publish_state: AssignmentPublishState;
};

export type AssignmentType = "coding" | "document" | "quiz";

export type AuthErrorResponse = {
  detail: string;
};

export type AuthProvider = "password";

export type CourseSummary = {
  id: string;
  course_code: string;
  title: string;
  term: string;
};

export type CreateCourseAssignmentInput = {
  title: string;
  description: string;
  assignment_type: AssignmentType;
  publish_state?: AssignmentPublishState;
};

export type HTTPValidationError = {
  detail?: ValidationError[];
};

export type HealthResponse = {
  status: string;
  app_name: string;
  service_name: string;
  layer: string;
  persistence_provider: string;
  workspace_packages: string[];
};

export type LoginRequest = {
  email: string;
  password: string;
};

export type SessionResponse = {
  user: SessionUser;
  provider: AuthProvider;
  expires_at: string;
};

export type SessionUser = {
  id: string;
  email: string;
  display_name: string;
};

export type SignupRequest = {
  email: string;
  display_name: string;
  password: string;
};

export type UpdateAssignmentInput = {
  title?: string | null;
  description?: string | null;
  assignment_type?: AssignmentType | null;
  publish_state?: AssignmentPublishState | null;
};

export type ValidationError = {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
};

export const apiClient = {
  signup(payload: SignupRequest) {
    return requestJson<SessionResponse>("/api/v1/auth/signup", {
      method: "POST",
      body: JSON.stringify(payload)
    });
  },
  login(payload: LoginRequest) {
    return requestJson<SessionResponse>("/api/v1/auth/login", {
      method: "POST",
      body: JSON.stringify(payload)
    });
  },
  logout() {
    return requestVoid("/api/v1/auth/logout", {
      method: "POST"
    });
  },
  getSession() {
    return requestJson<SessionResponse>("/api/v1/auth/session", {
      method: "GET"
    });
  },
  listManagedCourses() {
    return requestJson<CourseSummary[]>("/api/v1/courses/managed", {
      method: "GET"
    });
  },
  listCourseAssignments(pathParams: { course_id: string; }) {
    return requestJson<AssignmentSummary[]>(`/api/v1/courses/${encodeURIComponent(pathParams.course_id)}/assignments`, {
      method: "GET"
    });
  },
  createCourseAssignment(pathParams: { course_id: string; }, payload: CreateCourseAssignmentInput) {
    return requestJson<AssignmentDetail>(`/api/v1/courses/${encodeURIComponent(pathParams.course_id)}/assignments`, {
      method: "POST",
      body: JSON.stringify(payload)
    });
  },
  getCourseAssignment(pathParams: { course_id: string; assignment_id: string; }) {
    return requestJson<AssignmentDetail>(`/api/v1/courses/${encodeURIComponent(pathParams.course_id)}/assignments/${encodeURIComponent(pathParams.assignment_id)}`, {
      method: "GET"
    });
  },
  updateCourseAssignment(pathParams: { course_id: string; assignment_id: string; }, payload: UpdateAssignmentInput) {
    return requestJson<AssignmentDetail>(`/api/v1/courses/${encodeURIComponent(pathParams.course_id)}/assignments/${encodeURIComponent(pathParams.assignment_id)}`, {
      method: "PATCH",
      body: JSON.stringify(payload)
    });
  },
  healthcheckHealthGet() {
    return requestJson<HealthResponse>("/health", {
      method: "GET"
    });
  },
} as const;
